server:
  port: 8080

stripe:
  secretKey: ${STRIPE_SECRET_KEY}
  webhookSecret: ${WEBHOOK_SECRET}
spring:
  application:
    name: freelancer

  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}
    region:
      static: ap-south-1
    stack:
      auto: false
    s3:
      bucket: freelance-marketplace-dev-images 



logging:
  level:
    org:
      springframework: 
        security: DEBUG
